### ISSUE TITLE
int vs double

### ISSUE THREAD

**Issue by llelf** [Sentenai/py-sentenai#27]
https://github.com/Sentenai/py-sentenai/blob/4e589996d65058166b9b566043b90c2c70ddecfe/sentenai/flare.py#L370

any particular reason?

**Comment by brandly** [comment]
good question. @xnomagichash is this a typo? looks like we should have `vt = 'int'` here (and better testing to enforce it)

**Comment by xnomagichash** [comment]
This is not a typo, but is conservative behavior based on the fact that there will always be floating point indexes available (even for integers) until we turn on schema enforcement. Until then, we can always use the floating point index and not hit weird edge cases where (because js only has floating point number) we have a few values pass integer validation, creating a sparse integer index. Right now we'd just use that index and give back awful results, so pegging numbers to the double index eliminates errors.

**Comment by brandly** [comment]
@xnomagichash should we do the same thing in the JS library? we currently use `Number.isInteger`:

https://github.com/Sentenai/js-sentenai/blob/0a250cceaf8eff16b3c7ceb15e4ab2577fc4f2e7/src/flare.js#L262

**Comment by xnomagichash** [comment]
@brandly Yes, definitely.
