### ISSUE TITLE
Had to `brew install geos` to get this installed

### ISSUE THREAD

**Issue by brandly** [Sentenai/py-sentenai#8]
is this normal? worth documenting somewhere?

**Comment by xnomagichash** [comment]
It's definitely worth documenting. I never encountered this issue on Mac OS (I did on FreeBSD, however) because I installed everything through the Anaconda distribution of Python.

Could you confirm that you're installing without Anaconda installed and that no other `brew install` invocations were needed for other items (like numpy)?

**Comment by brandly** [comment]
Ah I see. I've seen Anaconda mentioned around, but I've never used it.

I've previously installed numpy, so if I needed other brew packages, it
would've been a while ago and I unfortunately can't remember.

Have a good weekend!

**Comment by stites** [comment]
@xnomagichash I had the same problem installing on ubuntu. `shapely` has a transitive dependency on `geos` which is implicitly handled by Anaconda.

**Comment by stites** [comment]
addressed in #19
